"""remove unique constraint from quantity

Revision ID: 48cbc967b2fe
Revises: 67428a2cfd94
Create Date: 2025-09-26 11:59:06.438795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cbc967b2fe'
down_revision: Union[str, Sequence[str], None] = '67428a2cfd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_quantity_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_quantity_key'), 'products', ['quantity'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
