"""add user_id to products

Revision ID: 8f373889860b
Revises: 48cbc967b2fe
Create Date: 2025-10-07 18:11:36.826657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f373889860b'
down_revision: Union[str, Sequence[str], None] = '48cbc967b2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
